### ISSUE TITLE
(OHS) HTML Native vs Non-native widgets

### ISSUE THREAD

**Issue by Tamayuzu** [MeD-DMC/Adapt-accessibilityfixes#118] opened 2021-07-27 18:13 UTC
https://accessibleweb.com/question-answer/what-is-the-difference-between-native-and-custom-widgets/

What are Wai-Aria widget roles? What are all the possible ones?
https://www.w3.org/TR/wai-aria-practices-1.1/#aria_ex

Each accordion header button is wrapped in an element with role heading that has a value set for aria-level that is appropriate for the information architecture of the page.

Skip to content
Should it be a link?
https://www.w3.org/TR/WCAG20-TECHS/G1.html

**Comment by MeD-Owner** [comment] 2022-01-17 16:43
Duplicate of #145

Merged and closing this one

**Closed by MeD-Owner** 2022-01-17 16:43 UTC
Labels: OHS
